<h3> Pandas A Comprehensive Overview for Machine Learning and Data Science </h3>

In [1]:
import pandas as pd

DataFrames- Kinda like Spreadsheets for Pandas

In [2]:
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['A',"B","C"],index=[1,2])

In [3]:
type(df) #to see the type

pandas.core.frame.DataFrame

In [4]:
df.head() # Returns the first 5 rows of a DataFrame or Series by default. 
df.head(1) #see the first row of the dataframe

   A  B  C
1  1  2  3

In [5]:
df.tail(1) #see the last row of the dataframe

   A  B  C
2  4  5  6

In [6]:
df.columns #we dont use brackets cause this is an attribute not a method

Index(['A', 'B', 'C'], dtype='object')

In [7]:

df.index.tolist()

[1, 2]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       2 non-null      int64
 1   B       2 non-null      int64
 2   C       2 non-null      int64
dtypes: int64(3)
memory usage: 64.0 bytes

In [9]:
df.describe()

             A        B        C
count  2.00000  2.00000  2.00000
mean   2.50000  3.50000  4.50000
std    2.12132  2.12132  2.12132
min    1.00000  2.00000  3.00000
25%    1.75000  2.75000  3.75000
50%    2.50000  3.50000  4.50000
75%    3.25000  4.25000  5.25000
max    4.00000  5.00000  6.00000

In [10]:
df.nunique()
df["A"].unique()

array([1, 4])

In [11]:
df.shape

(2, 3)

In [12]:
df.head()

   A  B  C
1  1  2  3
2  4  5  6